import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import EmotionProvider from "./EmotionProvider";
import { NotificationProvider } from "@/context/NotificationContext";
import MuiThemeProvider from "@/MuiThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({ 
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${geistSans.variable} ${geistMono.variable}`}>
      <EmotionProvider>
      <MuiThemeProvider>
        <NotificationProvider>
          {children}
        </NotificationProvider>
        </MuiThemeProvider>
      </EmotionProvider>
      </body>
    </html>
  );
}
